# GoReleaser config
project_name: mediax
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    binary: mediax
    flags:
      - -tags=release
    ldflags:
      - -s -w -X github.com/scenery/mediax/version.Version={{ .Version }} -X github.com/scenery/mediax/version.CommitSHA={{ .ShortCommit }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  version_template: "{{ .Tag }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^ci:'
      - '^style:'